// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiD7cMxRpDauXenVHRZQvq-cVDuWlAdz0',
    appId: '1:166365589002:web:f921b3c676a8fc2f6279f3',
    messagingSenderId: '166365589002',
    projectId: 'p-inz-719da',
    authDomain: 'p-inz-719da.firebaseapp.com',
    storageBucket: 'p-inz-719da.firebasestorage.app',
    measurementId: 'G-ZW7Z0S41QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqv0CUAsWClIKqPntKo0oMO1zd1rWQikw',
    appId: '1:166365589002:android:b8c6d2fbc6b386c26279f3',
    messagingSenderId: '166365589002',
    projectId: 'p-inz-719da',
    storageBucket: 'p-inz-719da.firebasestorage.app',
  );

}